### PR TITLE
Add getComposedInstance which returns the composed component instance

### PR DESCRIPTION
**Pull request by frenzzy**
It allow to [expose component functions](https://facebook.github.io/react/tips/expose-component-functions.html) through withStyles decorator.

See #26, #27

### CODE REVIEW

**Comment by koistya** [comment]
For review @jasonsanjose, @clempat, @joshduck :innocent:

**Comment by clempat** [comment]
This is the solution, thanks. But I guess will have the same issue than react-redux for stateless component. or? https://github.com/reactjs/react-redux/issues/141. I don't know what is the most elegant solution. 

I made workaround in my application passing the context this to parent callback through props.

**Comment by adriantoine** [comment]
That would be really helpful, what is the status of this PR? @frenzzy @koistya

**Comment by odub** [comment]
Keen to use this!

**Comment by frenzzy** [comment]
Better approach here: https://github.com/kriasoft/react-starter-kit/issues/909#issuecomment-252969542

**Pull request closed without merging**
