### PR TITLE
Correct error with 'insertCss' requirement.

### PR DESCRIPTION
**Pull request by luigifreitas**

### CODE REVIEW

**Comment by navgarcha** [comment]
Will this be merged at any point?

**Comment by pmaciejewski** [comment]
Is there any chance to have that merged or the same functionality provided? Same as for @navgarcha it causes issues with enzyme.

**Comment by navgarcha** [comment]
@pmaciejewski feel free to use my temp repo in your project in the meantime - its just a cut of the project but obviously won't be maintained perfectly in sync with the main repo: https://www.npmjs.com/package/temp-isomorphic-style-loader

**Comment by frenzzy** [comment]
Why can't you use mock or just provide react context in tests?

**Comment by frenzzy** [comment]
Thank you! Closing in favor of #104 and #141

**Pull request closed without merging**
