### PR TITLE
Support useStyles(style) for Hooks

### LINKED ISSUE #154: Hook?
It would be great if this library added a hook in additiona to the withStyles HOC.
Any plans ?

### PR DESCRIPTION
**Pull request by piglovesyou**
Fixes #154.

I'm glad if you take a look this, @frenzzy .

### CODE REVIEW

**Comment by piglovesyou** [comment]
Glad if you take a look at this, @frenzzy .

**Comment by frenzzy** [comment]
I think all react-related stuff should be moved away from `isomorphic-style-loader` package.
Since webpack loaders usually are dev-dependencies but react HOC/hook must be a dependency.
See also #156

**Comment by piglovesyou** [comment]
@frenzzy Thank you for the information, that's a good discussion. Yes, I'll follow decision the issue will make. Or, we can move withStyles and useStyles together later, since useStyles is just another implementation of withStyles.

**Comment by piglovesyou** [comment]
@frenzzy Do you have a plan to separate the package into a loader and a react binding? That would be a breaking change. Would you like me to create the PR?

**Comment by frenzzy** [comment]
> Or, we can move withStyles and useStyles together later, since useStyles is just another implementation of withStyles.

Agreed. Let's do this, I will release it as `v5.1.0` today.

> Do you have a plan to separate the package into a loader and a react binding? That would be a breaking change. Would you like me to create the PR?

It would be nice to split them, but I don't have time to do it. Need to create another repo for react bindings, configure builds, write tests etc. After that make a PR to `isomorphic-style-loader` with removed react stuff and special docs. Breaking change is not a problem I believe, we will just increase version number to v6. Help is really appreciated here, I even consider adding a new maintainers to this repo.

**Comment by frenzzy** [comment]
Released as [v5.1.0](https://github.com/kriasoft/isomorphic-style-loader/releases/tag/v5.1.0) :tada:

**Comment by piglovesyou** [comment]
Thank you frenzzy. Yeah, that is going to be some work. I see, you're thinking another GitHub repo for it. I think I'll give it a try in the next *free* weekends.

**Comment by piglovesyou** [comment]
@frenzzy Instead of separating the repo, what would you say if we about monorepo with [Lerna](https://lerna.js.org/)?

#### Pros
* Documenting in one place (root `README.md`) - Easy to read and easy to maintain
* Easy to track for each packages' change for maintainers - Lerna has a functionality to link to each other
* Possibly we can provide Vue.js binding as third package in the monorepo

#### Cons
* Increase complication of codebase a bit - But this is inevitable when we separate it anyway
* I'm still not sure Lerna is the right choice (Only two packages. Should it be worth for us?)

**Comment by piglovesyou** [comment]
We finished this talk on https://github.com/kriasoft/isomorphic-style-loader/pull/160#issuecomment-502370810

**Pull request merged**
